name: 自动1

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: "0 0 1,5 * *"  # 每月1号运行一次

jobs:
  run-coco1:
    runs-on: ubuntu-latest

    env:
      LOGIN_URL: ${{ secrets.LOGIN_URL1 }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install requests paramiko urllib3

      - name: 运行采集脚本
        run: python -u bb1.py | tee output.log

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: 保持仓库活跃
        uses: liskin/gh-workflow-keepalive@v1
